Read-me file
multiversx/mx-chain-simulator-go pull request #2
Opened 2023-11-13 09:45 UTC by miiu96

2023-11-15 12:47 UTC, iulianpascalau requested changes

2023-11-15 12:47 UTC, iulianpascalau commented on .github/workflows/pr-tests.yml
> +          go test ./...
missing empty line

2023-11-15 13:12 UTC, miiu96 commented on .github/workflows/pr-tests.yml
> +          go test ./...
added

2023-11-15 13:13 UTC, miiu96 commented on Dockerfile
> +FROM golang:1.20.5 as builder
changed

2023-11-15 13:13 UTC, miiu96 commented on cmd/chainsimulator/config/config.toml
> +        logs-path = "logs"
added

2023-11-15 13:14 UTC, miiu96 commented on README.md
> +- `simulator/initial-wallets`: This endpoint will return the initial wallets (address and private key hex encoded)
will extend the README in the next PR.

2023-11-15 13:18 UTC, miiu96 commented on pkg/proxy/configs/configsFetcher.go
> +	} else if err != nil {
removed

2023-11-15 13:27 UTC, miiu96 commented on pkg/proxy/configs/configsFetcher.go
> +		return out.Close()
fixed

2023-11-15 14:06 UTC, miiu96 commented on pkg/proxy/configs/configsFetcher_test.go
> +func TestConfigsFetcher(t *testing.T) {
refactored

2023-11-15 14:22 UTC, miiu96 commented on cmd/chainsimulator/main.go
>  	startTime := time.Now().Unix()
done.

2023-11-15 15:27 UTC, miiu96 commented on pkg/proxy/configs/configs.go
> +	pemFile := path.Join(newConfigsPath, "walletKey.pem")
done

2023-11-15 15:27 UTC, miiu96 commented on pkg/proxy/configs/configsFetcher.go
> +func NewConfigsFetcher(mxChainNodeRepo, mxChainProxy string, git GitHandler) (*fetcher, error) {
added

2023-11-15 15:31 UTC, miiu96 commented on testscommon/gitFetcherStub.go
> +type GitFetcherStub struct {
added

2023-11-15 17:14 UTC, sstanculeanu approved these changes

2023-11-16 14:02 UTC, iulianpascalau reviewed
just the extra flags

2023-11-16 14:15 UTC, miiu96 commented
> just the extra flags

done

2023-11-16 14:25 UTC, sstanculeanu approved these changes

2023-11-17 08:05 UTC, iulianpascalau approved these changes

2023-11-17 08:05 UTC, merged